### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ggold7046**
Fixed typo.

### CODE REVIEW

**Comment by mshudrak** [comment]
Hi @ggold7046, thank you for your interest in the project. We had one pull request changing README.md earlier than yours. Could you please merge it with this one? Could you also please merge your 3 other requests into one pull request.

Thank you.

**Comment by ggold7046** [comment]
> Could you please merge it with this one?

Hi @mshudrak , I don't know which pull request was created and how to merge my pull request with that one.



> Could you also please merge your 3 other requests into one pull request.

I also don't know how to merge all 3 PRs into one.

**Comment by mshudrak** [comment]
Well, one option is to just cancel those 4 and submit just one with all changes together.

**Comment by ggold7046** [comment]
@mshudrak , I have closed all the pull request . Do you anything easy issues for me ? I saw all the good first issues are taken

**Comment by ggold7046** [comment]
Hi @mshudrak , I saw this project is under gsoc'23 (https://github.com/google/gcp_scanner/wiki/Google-Summer-of-Code-2023#application-guideline) . And I saw that the application guidelines is asking to contribute to one of the Good first issue. But as all the easy issues are taken, what should I do to qualify for this project for gsoc'23 ?

**Comment by mshudrak** [comment]
You can choose any other issues not marked as Good first issue. You already created commit to fix grammar in README.md. Why would not you just resubmit it as just single commit like I suggested above?

**Comment by ggold7046** [comment]
> Why would not you just resubmit it as just single commit like I suggested above?

You told me someone already opened a PR, and I should merge all the PRs with it. But I don't know, how to merge a PR with others PRs.

**Pull request closed without merging**
