### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by ro4i7**
## Description

[I have made the necessary update  for issues # 94, #47]

## Changes Made
[I have updated the contributing.md  and crawl.py for issues #94, and #47 ]

## Checklist
- [x] I have read and followed the contributing guidelines.
- [ ] I have tested my changes thoroughly and they work as expected.
- [ ] I have added necessary tests for the changes made.
- [ ] I have updated the documentation to reflect the changes made.
- [ ] My code follows the project's coding style and standards.
- [ ] I have added appropriate commit messages and comments for my changes.

## Related Issues
[If your changes relate to any existing issues, please list them here.]

## Additional Notes
[Provide any additional notes or context that may be helpful for the reviewers.]

Feel free to modify and customize this template as needed to fit the specific needs of the GCP Scanner project.

### CODE REVIEW

**Comment by ZetaTwo** [comment]
Can you please split the PR into two, one for each issue since they are unrelated issues? Also you are currently linking to PRs, not issues.

**Review by ZetaTwo — CHANGES_REQUESTED** [review]
Please split into separate PRs

**Comment by ro4i7** [comment]
> Please split into separate PRs

@ZetaTwo Ok, I am doing it.

**Comment by ro4i7** [comment]
> > Please split into separate PRs
> 
> @ZetaTwo Ok, I am doing it.

@ZetaTwo @mshudrak i have done the splitting. new upadated CONTRIBUTING.md PR --> [link](https://github.com/google/gcp_scanner/pull/97)

**Comment by ro4i7** [comment]
i have updated this PR in [link](https://github.com/google/gcp_scanner/pull/97). So, I'm closing this PR. Please give feedback there. @ZetaTwo @mshudrak

**Comment by ro4i7** [comment]
ok

**Pull request closed without merging**
