### PR TITLE
updated logging format

### PR DESCRIPTION
**Pull request by Am0stafa**
## How to Test
This change should not affect the functionality of the project. To test, simply run the project and verify that the expected log messages are displayed in the console or log file.

## Related Issues
None.

## Type of Change
- [x] Bug fix
- [x] New feature
- [ ] Breaking change
- [ ] Documentation update

## Checklist
- [x] I have tested this change thoroughly.
- [x] I have added appropriate comments to the code for future reference.
- [x] I have updated the documentation (if applicable).

### CODE REVIEW

**Comment by Am0stafa** [comment]
What do you think about configuring the logs such that the logs are saved in a file rather than printed in the console?

**Comment by Am0stafa** [comment]
Honestly i have no clue why the tests are failing can someone guild me on why and how to fix it, i just changed the logging formate along with change in the logging of an error message

**Comment by ZetaTwo** [comment]
> What do you think about configuring the logs such that the logs are saved in a file rather than printed in the console?

by default, no

**Comment by Am0stafa** [comment]
@ZetaTwo should it be a feature or its not worth it?
it can be done by adding an argument such as -f or --log-file option to specify whether they want to log into a file or not, after that we can use that flag to determine whether or not to log into a file.
and finally, update the documentation.

**Comment by Am0stafa** [comment]
I think it would be helpful such that if someone wants all the logs but doesn't want them in the console

**Comment by mshudrak** [comment]
Tests are failing. PTAL.

**Comment by Am0stafa** [comment]
@mshudrak i really cant understand why the tests are falling i tried debugging them by removing all the changes and still they are failing can you guide me on why that test is failing and how to fix it

**Comment by Am0stafa** [comment]
@mshudrak I literally removed all changes and still getting the same error 445093c , what do you think is the cause of the problem and does anyone has any suggestions?

**Comment by mshudrak** [comment]
@Am0stafa this is a problem with our test workflow, it is failing because GCP API response has changed and we expect different output. I am going to fix it now.

**Comment by Am0stafa** [comment]
Yeah now it passes all the tests

**Comment by mshudrak** [comment]
I will let @ZetaTwo approve or make any other suggestions on this one.

**Review by ZetaTwo — APPROVED** [review]

**Pull request merged**
