### PR TITLE
refactor: Crawler/sql instances

### LINKED ISSUE #205: Subtasks: Implement crawl factory for SQL instances resource.
#153

### PR DESCRIPTION
**Pull request by peb-peb**
## Notes

closes #205 
ref #153 

@mxmssh @ZetaTwo

### CODE REVIEW

**Review by ZetaTwo — APPROVED** [review]

**Comment by ZetaTwo** [comment]
Looks good but there are conflicts that need to be resolved

**Comment by ZetaTwo** [comment]
Still merge conflicts unfortunately.

**Review by ZetaTwo — APPROVED** [review]

**Comment by ZetaTwo** [comment]
Conflicts probably caused by the other merge.

**Comment by peb-peb** [comment]
resolved!

**Review by ZetaTwo — APPROVED** [review]

**Pull request merged**
