### PR TITLE
ci: Enable versioning

### PR DESCRIPTION
**Pull request by sumit-158**
## Description
- Enable release-please-action

## Fix
- #20

### CODE REVIEW

**Comment by mshudrak** [comment]
We also need to update PR name to better reflect what we are doing here.

**Comment by sumit-158** [comment]
> Have you tested this workflow in your own repository?

Yes, [here](https://github.com/sumit-158/release-please-action/pull/4) (Its just a test repository)

> Could you also customize names and make release only when certain tag is pushed (we want tag-based release schema).

You mean "changelog-types" in my latest commit.

Also, we can change "release-type" to python currently it in simple

**Comment by mshudrak** [comment]
> > Have you tested this workflow in your own repository?
> 
> Yes, [here](https://github.com/sumit-158/release-please-action/releases) (It just test repository)
> 
> > Could you also customize names and make release only when certain tag is pushed (we want tag-based release schema).
> 
> You mean "changelog-types" in my latest commit.
> 
> * we can change "release-type" to python currently it is simple.
> * Also, we have to "Allow GitHub Actions to create and approve pull requests" (If we haven't already) in "Actions permission"

As far as I understand, we create new release on every push commit, right? This is redundant, we would prefer to have some "mechanism" to tell release-action to create release only for certain commits (e.g. commit with certain tag or may be to certain branch). I'd encourage you to think about the best strategy here.

**Comment by sumit-158** [comment]
@mshudrak What about triggering it when pushing a commit with the prefix maybe "release", what are your thoughts?

**Comment by sumit-158** [comment]
> As far as I understand, we create new release on every push commit, right? 

Not, exactly It just creates a new Pr with contains all previous commit like [here ](https://github.com/sumit-158/release-please-action/pull/8), If we have to create a new release then we just have to merge release-please PR!

**Comment by sumit-158** [comment]
> How often does it generate those PRs? 

Every time we merge the pr and any new push commit happenes.

> Is that literally for each commit with conventional message?

Yes, those which are mentioned in changelog-type.

**Comment by mshudrak** [comment]
Ok, let me think about that solution and PR #98. I am a bit skeptical having extra PR on almost every push we make...

**Comment by sumit-158** [comment]
Sure @mshudrak , Just putting It won't create extra PR for every single push it's just a single PR will keep track of almost every Push...

**Review by mshudrak — APPROVED** [review]

**Comment by mshudrak** [comment]
Ok, let's try this one.

**Pull request merged**
