### PR TITLE
refactor: Crawler/filestore instances

### LINKED ISSUE #201: Subtasks: Implement crawl factory for FileStore resource.
**Additional Context:**
#153

### PR DESCRIPTION
**Pull request by peb-peb**
## Notes

closes #201 
ref to #153

@mxmssh @ZetaTwo

### CODE REVIEW

**Review by ZetaTwo — APPROVED** [review]

**Comment by ZetaTwo** [comment]
Looks good but there are conflicts. Please check.

**Comment by ZetaTwo** [comment]
New merge conflicts

**Comment by peb-peb** [comment]
resolved!

**Comment by peb-peb** [comment]
I guess all the PRs would have conflicts as we merge each.

**Review by ZetaTwo — APPROVED** [review]

**Pull request merged**
